from planner.tax.autonomo import (
    Actividad,
    actividad,
    gastos_dificil_justificacion,
    rendimiento_neto,
    reta_tramo,
)
from planner.tax.compensacion import (
    BaseAhorro,
    BaseGeneral,
    base_imponible_ahorro,
    compensar_base_liquidable_general,
    pendientes_vacios,
)
from planner.tax.cotizacion import cotizacion_trabajador
from planner.tax.inmuebles import (
    REDUCCIONES_ARRENDAMIENTO,
    Arrendamiento,
    amortizacion_inmueble,
    ganancia_exenta_vivienda,
    impuesto_compra_vivienda,
    imputacion_renta,
    rendimiento_arrendamiento,
)
from planner.tax.irpf import (
    IrpfAnual,
    RentasMiembro,
    cuota_integra,
    cuota_integra_mitad,
    irpf_anual,
    irpf_conjunta,
)
from planner.tax.minimos import (
    Discapacidad,
    Familiar,
    Mitades,
    Persona,
    minimo_conjunta,
    minimo_personal_familiar,
)
from planner.tax.reducciones import (
    reduccion_actividad,
    reduccion_prevision_social,
    rendimiento_trabajo,
)
from planner.tax.rules import (
    ActividadRules,
    CotizacionRules,
    Inmuebles,
    IrpfRules,
    RetaRules,
    RetaTramo,
    available_years,
    load_irpf_rules,
    rules_for_year,
)
from planner.tax.scale import Bracket, Scale, load_scale

__all__ = [
    "REDUCCIONES_ARRENDAMIENTO",
    "Actividad",
    "ActividadRules",
    "Arrendamiento",
    "BaseAhorro",
    "BaseGeneral",
    "Bracket",
    "CotizacionRules",
    "Discapacidad",
    "Familiar",
    "Inmuebles",
    "IrpfAnual",
    "IrpfRules",
    "Mitades",
    "Persona",
    "RentasMiembro",
    "RetaRules",
    "RetaTramo",
    "Scale",
    "actividad",
    "amortizacion_inmueble",
    "available_years",
    "base_imponible_ahorro",
    "compensar_base_liquidable_general",
    "cotizacion_trabajador",
    "cuota_integra",
    "cuota_integra_mitad",
    "ganancia_exenta_vivienda",
    "gastos_dificil_justificacion",
    "impuesto_compra_vivienda",
    "imputacion_renta",
    "irpf_anual",
    "irpf_conjunta",
    "load_irpf_rules",
    "load_scale",
    "minimo_conjunta",
    "minimo_personal_familiar",
    "pendientes_vacios",
    "reduccion_actividad",
    "reduccion_prevision_social",
    "rendimiento_arrendamiento",
    "rendimiento_neto",
    "rendimiento_trabajo",
    "reta_tramo",
    "rules_for_year",
]
